services:
  frontend:
    build: frontend
    ports:
      - "3010:8080"
    links:
      - backend
  backend:
    build: backend
    ports:
      - "3011:8080"
    volumes:
      - "~/.aws:/root/.aws"
    links:
      - redis
  redis:
    image: redislabs/rejson
    ports:
      - "6379:6379"